name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Feature requests are welcome. If the idea aligns with the project roadmap, it will be prioritized accordingly.

        Please describe your idea clearly — the more context, the better.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? Why do you need it?
      placeholder: I'm trying to ... but currently ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work? Be as specific as you want.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds or considered other approaches?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, examples, or references.
    validations:
      required: false
